INSERT INTO uf (acronym, name) VALUES
('AC', 'Acre'),
('AL', 'Alagoas'),
('AP', 'Amapá'),
('AM', 'Amazonas'),
('BA', 'Bahia'),
('CE', 'Ceará'),
('DF', 'Distrito Federal'),
('ES', 'Espírito Santo'),
('GO', 'Goiás'),
('MA', 'Maranhão'),
('MT', 'Mato Grosso'),
('MS', 'Mato Grosso do Sul'),
('MG', 'Minas Gerais'),
('PA', 'Pará'),
('PB', 'Paraíba'),
('PR', 'Paraná'),
('PE', 'Pernambuco'),
('PI', 'Piauí'),
('RJ', 'Rio de Janeiro'),
('RN', 'Rio Grande do Norte'),
('RS', 'Rio Grande do Sul'),
('RO', 'Rondônia'),
('RR', 'Roraima'),
('SC', 'Santa Catarina'),
('SP', 'São Paulo'),
('SE', 'Sergipe'),
('TO', 'Tocantins');

INSERT INTO cities (name, uf_id) VALUES
('Rio Branco', 1),
('Cruzeiro do Sul', 1),
('Sena Madureira', 1),
('Tarauacá', 1),
('Xapuri', 1),

('Maceió', 2),
('Arapiraca', 2),
('Palmeira dos Índios', 2),
('Penedo', 2),
('São Miguel dos Campos', 2),

('Macapá', 3),
('Santana', 3),
('Laranjal do Jari', 3),
('Tartarugalzinho', 3),
('Mazagão', 3),

('Manaus', 4),
('Parintins', 4),
('Itacoatiara', 4),
('Tefé', 4),
('Tabatinga', 4),

('Salvador', 5),
('Feira de Santana', 5),
('Vitória da Conquista', 5),
('Camaçari', 5),
('Juazeiro', 5),

('Fortaleza', 6),
('Caucaia', 6),
('Maracanaú', 6),
('Sobral', 6),
('Crato', 6),

('Brasília', 7),
('Taguatinga', 7),
('Ceilândia', 7),
('Gama', 7),
('Planaltina', 7),

('Vitória', 8),
('Vila Velha', 8),
('Serra', 8),
('Cariacica', 8),
('Guarapari', 8),

('Goiânia', 9),
('Aparecida de Goiânia', 9),
('Anápolis', 9),
('Trindade', 9),
('Catalão', 9),

('São Luís', 10),
('Imperatriz', 10),
('Caxias', 10),
('Açailândia', 10),
('Bacabal', 10),

('Cuiabá', 11),
('Várzea Grande', 11),
('Rondonópolis', 11),
('Sinop', 11),
('Lucas do Rio Verde', 11),

('Campo Grande', 12),
('Dourados', 12),
('Três Lagoas', 12),
('Corumbá', 12),
('Ponta Porã', 12),

('Belo Horizonte', 13),
('Uberlândia', 13),
('Contagem', 13),
('Juiz de Fora', 13),
('Betim', 13),

('Belém', 14),
('Ananindeua', 14),
('Santaren', 14),
('Marabá', 14),
('Castanhal', 14),

('João Pessoa', 15),
('Campina Grande', 15),
('Patos', 15),
('Santa Rita', 15),
('Bayeux', 15),

('Curitiba', 16),
('Londrina', 16),
('Maringá', 16),
('Ponta Grossa', 16),
('Foz do Iguaçu', 16),

('Recife', 17),
('Olinda', 17),
('Jaboatão dos Guararapes', 17),
('Caruaru', 17),
('Petrolina', 17),

('Teresina', 18),
('Parnaíba', 18),
('Picos', 18),
('Floriano', 18),
('Oeiras', 18),

('Rio de Janeiro', 19),
('Niterói', 19),
('São Gonçalo', 19),
('Duque de Caxias', 19),
('Volta Redonda', 19),

('Natal', 20),
('Mossoró', 20),
('Parnamirim', 20),
('Caicó', 20),
('Currais Novos', 20),

('Porto Alegre', 21),
('Canoas', 21),
('Pelotas', 21),
('Gravataí', 21),
('Santa Maria', 21),

('Porto Velho', 22),
('Ji-Paraná', 22),
('Ariquemes', 22),
('Cacoal', 22),
('Rolim de Moura', 22),

('Boa Vista', 23),
('Rorainópolis', 23),
('Caracaraí', 23),
('Cantá', 23),
('Normandia', 23),

('Florianópolis', 24),
('Joinville', 24),
('Blumenau', 24),
('São José', 24),
('Chapecó', 24),

('São Paulo', 25),
('Campinas', 25),
('Santos', 25),
('São Bernardo do Campo', 25),
('Osasco', 25),

('Aracaju', 26),
('Lagarto', 26),
('Nossa Senhora do Socorro', 26),
('Itabaiana', 26),
('Estância', 26),

('Palmas', 27),
('Araguaína', 27),
('Gurupi', 27),
('Porto Nacional', 27),
('Tocantinópolis', 27);